branch-defaults:
  main:
    environment: jassgott-env
    group_suffix: null
global:
  application_name: jassgott
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.10
  default_region: eu-central-1  # or your preferred region
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
